version: "3.9"

services:
  serviceobjectreadability:
    build: .
    restart: always
    ports:
      - "5002:5002"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]